package org.folio.service.transformationfields;

import java.util.EnumSet;
import java.util.Set;

import static org.folio.service.transformationfields.TransformationFieldsConfig.*;

public class TransformationConfigConstants {

  protected static final Set<TransformationFieldsConfig> INSTANCE_FIELDS_CONFIGS = EnumSet.of(
    ALTERNATIVE_TITLES,
    EDITIONS,
    ELECTRONIC_ACCESS_URI,
    ELECTRONIC_ACCESS_LINKTEXT,
    ELECTRONIC_ACCESS_MATERIALS_SPECIFIED,
    ELECTRONIC_ACCESS_PUBLICNOTE,
    ELECTRONIC_ACCESS_URI_DEFAULT,
    ELECTRONIC_ACCESS_LINKTEXT_DEFAULT,
    ELECTRONIC_ACCESS_MATERIALS_SPECIFIED_DEFAULT,
    ELECTRONIC_ACCESS_PUBLICNOTE_DEFAULT,
    HR_ID,
    IDENTIFIERS,
    ID,
    INSTANCE_TYPE,
    MODE_OF_ISSUANCE_ID,
    LANGUAGES,
    SOURCE,
    SUBJECTS,
    LANGUAGES,
    METADATA_CREATED_DATE,
    METADATA_UPDATED_DATE,
    METADATA_CREATED_BY_USER_ID,
    METADATA_UPDATED_BY_USER_ID
  );

  protected static final Set<TransformationFieldsConfig> HOLDINGS_FIELDS_CONFIGS = EnumSet.of(
    ELECTRONIC_ACCESS_URI,
    ELECTRONIC_ACCESS_LINKTEXT,
    ELECTRONIC_ACCESS_MATERIALS_SPECIFIED,
    ELECTRONIC_ACCESS_PUBLICNOTE,
    ELECTRONIC_ACCESS_URI_DEFAULT,
    ELECTRONIC_ACCESS_LINKTEXT_DEFAULT,
    ELECTRONIC_ACCESS_MATERIALS_SPECIFIED_DEFAULT,
    ELECTRONIC_ACCESS_PUBLICNOTE_DEFAULT,
    ID,
    HR_ID,
    INSTANCE_ID,
    HOLDINGS_CALL_NUMBER,
    HOLDINGS_CALL_NUMBER_PREFIX,
    HOLDINGS_CALL_NUMBER_SUFFIX,
    HOLDINGS_CALL_NUMBER_TYPE,
    METADATA_CREATED_DATE,
    METADATA_CREATED_BY_USER_ID,
    METADATA_UPDATED_DATE,
    METADATA_UPDATED_BY_USER_ID
  );

  protected static final Set<TransformationFieldsConfig> ITEM_FIELDS_CONFIGS = EnumSet.of(
    ELECTRONIC_ACCESS_URI,
    ELECTRONIC_ACCESS_LINKTEXT,
    ELECTRONIC_ACCESS_MATERIALS_SPECIFIED,
    ELECTRONIC_ACCESS_PUBLICNOTE,
    ELECTRONIC_ACCESS_URI_DEFAULT,
    ELECTRONIC_ACCESS_LINKTEXT_DEFAULT,
    ELECTRONIC_ACCESS_MATERIALS_SPECIFIED_DEFAULT,
    ELECTRONIC_ACCESS_PUBLICNOTE_DEFAULT,
    HR_ID,
    ID,
    HOLDINGS_ID,
    BARCODE,
    VOLUME,
    ENUMERATION,
    CHRONOLOGY,
    YEARCAPTION,
    STATUS,
    DESCRIPTION_OF_PIECES,
    COPYNUMBER,
    NUMBER_OF_PIECES,
    MATERIAL_TYPE_ID,
    PERMANENT_LOAN_TYPE_ID,
    ITEM_CALL_NUMBER,
    ITEM_CALL_NUMBER_PREFIX,
    ITEM_CALL_NUMBER_SUFFIX,
    ITEM_CALL_NUMBER_TYPE,
    METADATA_CREATED_DATE,
    METADATA_UPDATED_DATE,
    METADATA_CREATED_BY_USER_ID,
    METADATA_UPDATED_BY_USER_ID
  );

  private TransformationConfigConstants() {
  }

}
