stages:
  - name: Build
    steps:
      - runScriptConfig:
          image: maven:3-openjdk-8
          shellScript: mvn package
  - name: Build Docker with DIND
    steps:
      - publishImageConfig:
          dockerfilePath: ./Dockerfile
          buildContext: .
          tag: docker.dev.folio.org/mod-data-export:concorde-latest
          pushRemote: true
          registry: docker.dev.folio.org
  - name: Deploy
    steps:
      - applyAppConfig:
          catalogTemplate: p-rlq5p:concorde-helmcharts-mod-data-export
          version: 0.1.10
          answers:
            image.repository: docker.dev.folio.org/mod-data-export
            image.tag: concorde-latest
          targetNamespace: concorde
          name: mod-data-export
timeout: 60
notification: {}
