openapi: 3.0.0
info:
  title: Data export
  version: v1
  description: Data export

servers:
  - url: https://stub.com/
paths:
  /stub:
    get:
      responses:
        "200":
          description: stub
