ALTER TABLE mapping_profiles ADD COLUMN IF NOT EXISTS locked BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE mapping_profiles ADD COLUMN IF NOT EXISTS locked_by UUID;
ALTER TABLE mapping_profiles ADD COLUMN IF NOT EXISTS locked_at TIMESTAMP;
