#%RAML 1.0

title: Data export
version: v2.0
protocols: [ HTTP, HTTPS ]
baseUri: https://github.com/folio-org/mod-data-export

documentation:
  - title: Data export Mapping Profile API
    content: APIs for managing Mapping Profiles

types:
  errors: !include raml-util/schemas/errors.schema
  mappingProfile: !include schemas/profiles/mappingProfile.json
  mappingProfileCollection: !include schemas/profiles/mappingProfileCollection.json
  UUID:
    type: string
    pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$


resourceTypes:
  collection: !include raml-util/rtypes/collection.raml
  collection-item: !include raml-util/rtypes/item-collection.raml

traits:
  validate: !include raml-util/traits/validation.raml
  pageable:  !include raml-util/traits/pageable.raml
  searchable: !include raml-util/traits/searchable.raml
  language: !include raml-util/traits/language.raml



/data-export/mapping-profiles:
    description: Service provides APIs supporting Mapping profiles
    type:
      collection:
        schemaCollection: mappingProfileCollection
        schemaItem: mappingProfile
        exampleCollection: !include samples/profiles/mappingProfileCollection.sample
        exampleItem: !include samples/profiles/mappingProfile.sample

    post:
      is: [validate]
    get:
      is: [ pageable, searchable: { description: "with valid searchable fields", example: "status=SUCCESS"}, validate ]
    /{id}:
      uriParameters:
        id:
          description: The UUID of a mapping Profile
          type: UUID
      displayName: Mapping Profile
      description: Get, Delete or Update a specific mapping Profile
      type:
        collection-item:
          schema: mappingProfile
          exampleItem: !include samples/profiles/mappingProfile.sample
