#%RAML 1.0

title: Data export
version: v1.0
protocols: [ HTTP, HTTPS ]
baseUri: http://localhost

documentation:
  - title: Data export API
    content: API for exporting MARC records

types:
  errors: !include raml-util/schemas/errors.schema
  exportRequest: !include schemas/exportRequest.json
  fileDefinition: !include schemas/fileDefinition.json

traits:
  validate: !include raml-util/traits/validation.raml

/data-export:
  /export:
    displayName: Export manager service
    description: Method to start export for MARC records
    post:
      description: Starts the export process
      is: [validate]
      body:
        application/json:
          type: exportRequest
      responses:
        204:
        400:
          description: "Bad request"
          body:
             text/plain:
               example: "Bad request"
        422:
          description: "Unprocessable Entity"
          body:
            application/json:
              type: errors
        500:
          description: "Internal server error"
          body:
            text/plain:
              example: "Internal server error"
  /fileDefinitions:
    displayName: File upload service
    description: Method to create file definition
    post:
      description: File definition
      is: [validate]
      body:
        application/json:
          type: fileDefinition
      responses:
        201:
          body:
            application/json:
              type: fileDefinition
        400:
          description: "Bad request"
          body:
            text/plain:
              example: "Bad request"
        422:
          description: "Unprocessable Entity"
          body:
            application/json:
              type: errors
        500:
          description: "Internal server error"
          body:
            text/plain:
              example: "Internal server error"
    /{fileDefinitionId}:
      get:
        description: Method to get File definition by id
        responses:
          200:
            body:
              application/json:
                type: fileDefinition
          400:
            description: "Bad request"
            body:
              text/plain:
                example: "Bad request"
          404:
            description: "Not found"
            body:
              text/plain:
                example: "Not found"
          500:
            description: "Internal server error"
            body:
              text/plain:
                example: "Internal server error"
      post:
        description: Upload file
        body:
            application/octet-stream:
        responses:
          200:
            body:
              application/json:
                type: fileDefinition
          400:
            description: "Bad request"
            body:
              text/plain:
                example: "Bad request"
          404:
            description: "Not found"
            body:
              text/plain:
                example: "Not found"
          500:
            description: "Internal server error"
            body:
              text/plain:
                example: "Internal server error"
