#%RAML 1.0

title: Data export
version: v1.0
protocols: [ HTTP, HTTPS ]
baseUri: https://github.com/folio-org/mod-data-export

documentation:
  - title: Data export API
    content: API for exporting MARC records

types:
  errors: !include raml-util/schemas/errors.schema
  fileDefinition: !include schemas/fileDefinition.json

traits:
  validate: !include raml-util/traits/validation.raml
  pageable:  !include raml-util/traits/pageable.raml
  searchable: !include raml-util/traits/searchable.raml
  language: !include raml-util/traits/language.raml



/data-export/fileDefinitions:
    displayName: File upload service
    description: Service provides APIs supporting file upload
    post:
      description: API to create file definition to use it for the file uploading
      is: [validate]
      body:
        application/json:
          type: fileDefinition
          example:
            value: !include samples/fileDefinition.sample
      responses:
        201:
          body:
            application/json:
              type: fileDefinition
        400:
          description: "Bad request"
          body:
            text/plain:
              example: "Bad request"
        422:
          description: "Unprocessable Entity"
          body:
            application/json:
              type: errors
        500:
          description: "Internal server error"
          body:
            text/plain:
              example: "Internal server error"
    /{fileDefinitionId}:
      get:
        description: Method to get file definition by id
        responses:
          200:
            body:
              application/json:
                type: fileDefinition
          400:
            description: "Bad request"
            body:
              text/plain:
                example: "Bad request"
          404:
            description: "Not found"
            body:
              text/plain:
                example: "Not found"
          500:
            description: "Internal server error"
            body:
              text/plain:
                example: "Internal server error"
      /upload:
        post:
          description: Method to upload file
          body:
              application/octet-stream:
          responses:
            200:
              body:
                application/json:
                  type: fileDefinition
            400:
              description: "Bad request"
              body:
                text/plain:
                  example: "Bad request"
            404:
              description: "Not found"
              body:
                text/plain:
                  example: "Not found"
            500:
              description: "Internal server error"
              body:
                text/plain:
                  example: "Internal server error"
